{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "edgequota.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgequota.labels" . | nindent 4 }}
  {{- with .Values.certificate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ .Values.certificate.secretName | default (printf "%s-tls" (include "edgequota.fullname" .)) }}
  {{- with .Values.certificate.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with .Values.certificate.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind | default "ClusterIssuer" }}
    {{- with .Values.certificate.issuerRef.group }}
    group: {{ . }}
    {{- end }}
  {{- with .Values.certificate.commonName }}
  commonName: {{ . }}
  {{- end }}
  {{- with .Values.certificate.dnsNames }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.ipAddresses }}
  ipAddresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
